version: '3.3'

services:
  web:
    build: .
    restart: "always"
    ports:
      - 3000:3000
    volumes:
    - .:/usr/src/app:rw
    command:
      - /bin/sh
      - -c
      - |
        echo "baeldung"
        echo "docker"
        yarn install
        yarn start 

